In [341]:
#!pip install matplotlib

In [342]:
!pip install tensorflow
!pip install seaborn

In [343]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

# Data loading and preprocessing

This data is readily available and already preprocessed in the keras library.

In [344]:
data = tf.keras.datasets.mnist.load_data()

In [345]:
data

((array([[[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         ...,
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0

In [346]:
(x_train, y_train), (x_test, y_test) = data

In [347]:
len(x_train)

60000

In [348]:
len(x_test)

10000

In [349]:
x_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

# Standardizing x data

In [350]:
x_train_std = (x_train / 255)
x_test_std = (x_test / 255)

# Flattening the x data

In [351]:
x_train_flattened = x_train_std.reshape(len(x_train_std),28*28)
x_test_flattened = x_test_std.reshape(len(x_test_std),28*28)

In [352]:
x_test_flattened.shape

(10000, 784)

# Building, compiling and training the neural network model 

In [353]:
model = Sequential([
    Dense(100,input_shape=(784,),activation='relu'),
    Dense(10,activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.fit(x_train_flattened,y_train,epochs=5)


Epoch 1/5
1875/1875 [==============================] - 1s 663us/step - loss: 0.2686 - accuracy: 0.9233
Epoch 2/5
1875/1875 [==============================] - 1s 667us/step - loss: 0.1235 - accuracy: 0.9635
Epoch 3/5
1875/1875 [==============================] - 1s 684us/step - loss: 0.0869 - accuracy: 0.9744
Epoch 4/5
1875/1875 [==============================] - 1s 633us/step - loss: 0.0671 - accuracy: 0.9797
Epoch 5/5
1875/1875 [==============================] - 1s 797us/step - loss: 0.0527 - accuracy: 0.9834


# Model evaluation

In [354]:
model.evaluate(x_test_flattened,y_test)

313/313 [==============================] - 0s 422us/step - loss: 0.0765 - accuracy: 0.9775


[0.07649785280227661, 0.9775000214576721]

In [355]:
x_test[2]


array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,  38, 254, 109,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,  87, 252,  82,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [356]:
y_pred = model.predict(x_test_flattened)

313/313 [==============================] - 0s 417us/step


In [357]:
y_pred[2]

array([9.0765866e-04, 9.9969763e-01, 5.9777230e-01, 3.8838819e-02,
       3.1382143e-01, 2.2107519e-02, 1.1828801e-01, 6.2488323e-01,
       3.8251185e-01, 5.7143508e-03], dtype=float32)

In [358]:
np.argmax(y_pred[2])

1

In [359]:
y_pred_labels = [np.argmax(i) for i in y_pred]
y_pred_labels[:5]

[7, 2, 1, 0, 4]

In [360]:
y_test[:5]

array([7, 2, 1, 0, 4], dtype=uint8)

In [361]:
cm = tf.math.confusion_matrix(labels = y_test, predictions = y_pred_labels)

In [362]:
plt.figure(figsize=(7,5))
sns.heatmap(cm, annot=True,fmt='d')
plt.xlabel('Prediction')
plt.ylabel('Truth')

Text(60.222222222222214, 0.5, 'Truth')

ImportError: cannot import name '_png' from 'matplotlib' (/Users/berinaspirjan/anaconda3/envs/neural_networks/lib/python3.8/site-packages/matplotlib/__init__.py)

<Figure size 700x500 with 2 Axes>